### ISSUE TITLE
New interface (beta) : does not draw tracks

### ISSUE THREAD

**Issue by tomchiverton** [eneiluj/gpxpod#15] opened 2023-03-26 16:29 UTC
Same files in old interface draws tracks on map fine.

**Comment by julien-nc** [comment] 2023-03-26 16:57
Can you provide one example file?

**Comment by tomchiverton** [comment] 2023-03-26 17:44
Had to rename from .gpx to .txt to trick GitHub into letting me upload : [PDW - Wildboarclough via Shutlingsloe walk.TXT](https://github.com/julien-nc/gpxpod/files/11072477/PDW.-.Wildboarclough.via.Shutlingsloe.walk.TXT)

**Comment by tomchiverton** [comment] 2023-03-26 17:53
To add some more color "zoom to bounds" works e.g. if I pan or zoom away, this is reset to where the old interface draws the track.

Due to #16 I'm using the OSM raster maps, if it helps.

Here is a screen shot:
![Screenshot_20230326_185307](https://user-images.githubusercontent.com/684204/227794614-df82d448-992d-4c4f-a8c4-aecaacf39e44.png)

**Comment by raud3rs** [comment] 2023-03-29 12:36
Hello
No maps showed in new interface.
https://nextcloud.raud3rs.syncloud.it:10443/apps/gpxpod/s/zWfYayPNAL5S5ej

**Comment by julien-nc** [comment] 2023-04-02 23:40
@tomchiverton Thanks for the bug report. Problem was your file contains a route and...routes support was actually not implemented yet. It's been added now and will be included in the next release coming soon. I also added support for waypoints (even with custom symbols like the old UI does).

@raud3rs This is a completely different issue. Next time, please create a new one :grin:.
This one is caused by a messy management of the CSP. It's now solved and it should be fine in the next release.
Here's a list of the upcoming improvements:
* maptiler is authorized in public pages
* the API keys are correctly injected in public pages (the share owner's ones or the admin ones)
* OSM raster tiles requests are not proxied to Nextcloud anymore
* add support for multi-sub-domain tile server URLs (like `https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png` where `{s}` can be replaced with `a`, `b` or `c`.
* and more fixes here and there

Btw [v5.0.7-1-nightly](https://github.com/julien-nc/gpxpod/releases/download/v5.0.7-1-nightly/gpxpod-5.0.7-1-nightly.tar.gz) is out. It would be awesome if one of you could try it.

**Comment by tomchiverton** [comment] 2023-04-05 16:30
I unpacked that over the top of the version I had from the Nextcloud built in "add app" thing.

My tracks appear in the new GUI now, thanks !

**Comment by julien-nc** [comment] 2023-04-05 17:01
Thanks for the feedback!

**Closed as completed by julien-nc** 2023-04-05 17:01 UTC
Labels: bug, question
